### PR TITLE
Run-Playbook Module Addition and Base Module Enhancements

### LINKED ISSUE #230: [Feature] Add MFA/SSPR User Status to Base Module
Add users MFA/SSPR status to base module

### LINKED ISSUE #299: [Feature] Run Playbook Module
Add a new STAT module that calls the Run Playbook API.  This will make it easier to call an existing remediation playbook in response to a triage performed by STAT.

For example, STAT may check Related alerts and TI and find something suspicious, which you then want to mark the user as compromised, instead of building the confirm compromise logic into the STAT playbook, you can use an existing Sentinel template, and simply run that playbook against the incident

https://docs.microsoft.com/en-us/rest/api/securityinsights/preview/incidents/run-playbook

### PR DESCRIPTION
**Pull request by briandelmsft**
* Fixes #299 
* Fixes #230
* Relates to #297

This PR includes the addition of a new module to allow you to run incident playbooks from STAT.  For example, if you wanted to use STAT to triage an incident and based on the outcome of that triage you could start another playbook that takes additional actions.

This also includes enhancements to the Base Module to retrieve and include SSPR & MFA registration data about the account entities.

[Deploy this PR](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Frunplaybook_deploy%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Frunplaybook_deploy%2FDeploy%2FcreateUiDefinition.json)

As this PR changes the deployment itself, after merging into main perform a test deployment from the main branch to confirm a deploy from that branch works as intended

### CODE REVIEW

**Comment by piaudonn** [comment]
Things work as expected 👍

There is a maybe unwanted side effect of returning a 500 to the coordinator for the Run-Playbook as it will cause the 4 retry (default behavior). Whereas there's no point of retrying. The actual module runs fines, but because it returns a 500, the caller tries again. I think that's fine as it should be granted permissions anyways for this to work.
I don't see the point of recommending to set the retry to 1 in the caller logic app as it is as much effort as to grant permissions (well as many action, just 1).

**Comment by piaudonn** [comment]
👆does this make sense?

**Comment by briandelmsft** [comment]
That does make sense to me.  I don't think there's a way in the custom connector to change the default retry policy... and I agree it's probably not worth nothing that it will retry as virtually everything in Logic apps will retry by default on failure

**Review by piaudonn — APPROVED** [review]
CousinIttAddamsFamilyGIF

**Pull request merged**
