### PR TITLE
Update API URL

### LINKED ISSUE #296: [BUG] MCAS Module - API Path Inconsistent with Docs
In the MCAS Module, we attempt to use the API path /cas/api/v1/entities/&lt;pk&gt;/ but the [docs](https://docs.microsoft.com/en-us/defender-cloud-apps/api-entities-fetch) indicate it should be /api/v1/entities/&lt;pk&gt;/

this change appeared in 8ea043c4d77065f78accc2fea6b8295ca03b4343 as the /cas/ wasn't originally included but I'm not sure why the change was made, or how it even worked as I verify it was working at the time but the module consistently fails for me until I change the path to as it is in the documentation.

I can easily fix this, but just wanted to check with you @piaudonn if you knew why this is there and if there is an issue changing it

### PR DESCRIPTION
**Pull request by piaudonn**
Fixes #296 
Well allegedly. As it is working consistently for some implementations with the /cas/ but after internal discussions, it should be /api

### CODE REVIEW

**Comment by briandelmsft** [comment]
2 things:

1. Doesn't the playbook version still need to be updated in the parameter in the azuredeploy.json to be picked up by the workbook?
2. What do you think about putting the API endpoint detection into an Until loop?  I just tested and I still had the failure... but I put it into an until loop, added a delay of 10 seconds between attempts and on the 3rd time through it found the right endpoint and the playbook worked successfully.

Something like:
image

**Comment by piaudonn** [comment]
I have zero failure with the proposed changed. Ran it 50 times.
Honestly, I don't know what's up with this API :/

**Comment by briandelmsft** [comment]
I only seem to see the problem when I haven't called the API for a while.  Almost like a free azure website or function that has to cold start on the first call, except instead of responding slowly it throws an error the first call or two.  That's why I'm suggesting the until loop, it will have no impact on performance if it succeeds the first time through the endpoint detection loop, but if it fails the first time it gives it a chance to succeed subsequently.

**Comment by briandelmsft** [comment]
@piaudonn I added the looping into PR #323 which is set to merge into this PR when complete.  can you give it a try and merge 323 when done

**Comment by piaudonn** [comment]
@briandelmsft should be okay. 
The loop seems to work fine after a simul of 100 runs. But I did them consecutively with no break. So, who knows...

**Comment by piaudonn** [comment]
Fixes #219 
I mean... why not... Not sure how to use that... No calculation, no avg... Raw data in there. Could be used in an email or some other comment/notification scenario I suppose.

**Review by briandelmsft — APPROVED** [review]

**Pull request merged**
