### PR TITLE
Adding Host support for Watchlist module and KQL Query bug

### LINKED ISSUE #285: [Feature] Host Entity Support for Watchlist Module
Add support for host entities in the watchlist module

### LINKED ISSUE #288: [BUG] KQLModule - M365 Query option fails to return data - length is null
The module runs successfully and comments the results to the incident but does not return a response to the calling logic app, due to a data type issue where length function running on a null

### PR DESCRIPTION
**Pull request by briandelmsft**
* Fixes #285 

When using the FQDN as the WatchlistKeyDataType we will attempt to match host entities to the WatchlistKey.

- Watchlist key should be in FQDN format
- Match is case insensitive
- The entity data can include FQDN or Hostname

___
* Fixes #288

When using the KQL module to query M365, the results are not returned to the calling logic app due to a value being null value being evaluated for length.  This issue is fixed and results should be returned for both M365 and Sentinel queries.
Also, increased the limit of data returned in the comments since the 30000 character comment limit is now in place.

This also fixes an entity escaping issue in the KQL, Related Alerts and UEBA modules

[Deploy Update](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Fvalidation_deploy%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Fvalidation_deploy%2FDeploy%2FcreateUiDefinition.json)

### CODE REVIEW

**Comment by piaudonn** [comment]
I think there's an issue if the SearchKey has a space in it. It's not a regression, it's just a scenario I have not tested before I think.
Unless I misunderstood what the SearchKey is or if we are maybe supposed to enter the quotes in the module input directly?
Am I making any sense?

**Comment by briandelmsft** [comment]
> I think there's an issue if the SearchKey has a space in it. It's not a regression, it's just a scenario I have not tested before I think.
> Unless I misunderstood what the SearchKey is or if we are maybe supposed to enter the quotes in the module input directly?
> Am I making any sense?

If there's a space in the searchkey you have to enter it as ['Search Key'] just like you would in an extend or project if the column has a space

**Comment by piaudonn** [comment]
Since many collumns have spaces in our watchlist templates: https://docs.microsoft.com/en-us/azure/sentinel/watchlist-schemas could we take care of it? Note necessarly in this PR.

**Comment by briandelmsft** [comment]
Probably, may be a bit awkward with the expression but should be possible.  There is a mention of it in the readme for the module so it is documented for now.

**Review by piaudonn — APPROVED** [review]

**Pull request merged**
