### PR TITLE
Add Hyperlink to Alerts in incident comments

### LINKED ISSUE #228: [Feature] Related Alerts - Link to related alerts
**Describe the solution you'd like**
In the related alerts comment, there should be an easy way to pivot to the related alerts (like a link to a KQL query that returns the alerts)

### PR DESCRIPTION
**Pull request by briandelmsft**
Fixes #228 

Make it easier to navigate to the alert to get additional details by hyperlinking the alert to a KQL query to pull it up in Log Search.

This adds about 600-800 characters per alert to the comment so we will need to wait for the rollout of the comment limit increase to 30,000 characters before merging this one

### CODE REVIEW

**Comment by briandelmsft** [comment]
@piaudonn you can test this at any point now... though it will only work today if their is only 1 (maybe 2) related alerts... beyond that it will hit the comment limit of 3000

**Comment by briandelmsft** [comment]
Looks great!  One small thing the incident comment seems to need a line break when there are multiple user entities:

image

**Comment by piaudonn** [comment]
Works even with 3 alerts (I guess I got lucjy with the entity name length or something.
I hit the "innerError": "Comment length should not exceed 3000 characters" after 3.

**Comment by briandelmsft** [comment]
I will work this change into another update of the related alerts module as this branch is now conflicting with other approved changes

**Pull request closed without merging**
