### PR TITLE
Adding Risk Scoring Module and KQL Support for Host Entities

### LINKED ISSUE #290: [Feature] Host Entity Support for KQL Module
Add host entity support for the KQL module, similar to the ipEntities and accountEntities we have today.

### LINKED ISSUE #291: [Feature] Risk Based Scoring
This new module will simplify the ability to determine the cumulative risks that other modules find and provide a consolidated score that can be used in a condition statement

For example, the related alerts module output can be dramatically different both in the number of related alerts that are found and the severity of those alerts.  Writing a condition statement to interpret the results can be complex as the you may need to account for both the quantity of alerts, but also the severity of those alerts.  With this scoring module we would take inputs from multiple modules like related alerts and return a consolidated score.

For related alerts we would use something such as a high risk alert = 10 points, medium = 5 points, low=3 points, informational=1 point.  A simple condition could then be written saying something like score >= 10.  This would fire if there was 1 high risk, or 2 mediums, or 4 lows, or any combinations >= 10

We will target the related alerts and KQL modules for the initial version

### LINKED ISSUE #292: Onboard Watchlists and TI to Risk Scoring
Onboard the Watchlist and TI modules to the risk scoring module

### LINKED ISSUE #293: [Feature] MDE Insights - Link enrichments to relevant device page
Get-MDEInsights -> Link each device to security portal device page (https://security.microsoft.com/machines/***MACHINEID***)

### LINKED ISSUE #294: [Feature] MCAS Module - Link user to the M365 User page
Get-MCASInvestigationScore -> Link to Security User Page (https://security.microsoft.com/user?aad=***AADUSERID***)

### LINKED ISSUE #301: [Feature] Add Tenant Info to Base Module Output
When building URLs to various portals, the TenantId may be needed.  This should be collected in the Base Module Body to be available to all modules

### PR DESCRIPTION
**Pull request by briandelmsft**
* Fixes #290 
* Fixes #291 
* Fixes #292 
* Fixes #301
* Fixes #294
* Fixes #293

This PR adds a new module to calculate risk scores.  It includes supporting inputs from Related Alerts, KQL, Watchlist and TI modules at this time.  The fundamental idea behind this is to simplify evaluating the relative risk of multiple module outputs.  While this is possible now with conditions, the conditions can get very complex if you are dealing with many modules.  By using a risk score, a score will be calculated for each module so that a condition can be as simple as if riskscore > x instead of looking at the results of each module individually.

Minor updates have been made to the supported modules (Related Alerts, KQL, Watchlist and TI) to pass the module name in the body so that the scoring module knows how to interpret the incoming data.  The TI module also has the additional of another output property, TotalTIMatchCount.  This is a simple sum of all the TI indicators that matched to make it easier to score.

This PR also includes an update to the KQL module to allow for passing of host entity data (table hostEntities) which is documented in the relevant readme in the riskscoring branch

**We will need to validate deployment succeeds after merge into main**

[Deploy this PR from test Branch](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Friskscore_deploy%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Friskscore_deploy%2FDeploy%2FcreateUiDefinition.json)

### CODE REVIEW

**Comment by piaudonn** [comment]
@briandelmsft What do you mean by

> We will need to validate deployment succeeds after merge into main

Is there more to test an install from scratch + a update on an already installed deployment?

**Comment by briandelmsft** [comment]
This PR also now

* Fixes #301
* Fixes #294
* Fixes #293

**Comment by briandelmsft** [comment]
@piaudonn I'll stop pushing to this branch now 😆

**Comment by piaudonn** [comment]
I'll test and validate this week. I am back in business!

**Review by piaudonn — APPROVED** [review]
Update 🟢

New deployment 🟢


Tried to mess a bit with the module calls and things run smooth. I approve 👍

**Comment by piaudonn** [comment]
I'll merge and test again then...

**Pull request merged**
