### PR TITLE
Connector Defaults and Base Module Comments

### LINKED ISSUE #218: STAT Connector - Assume Defaults
to make it quicker to call a STAT module, we may want to assume some defaults such as, always add comments to the incident and allow users to override.  Right now all inputs are required for all modules when it isn't entirely necessary.

This requires a change to the connector to no longer require these fields as mandatory and to the coordinator to send the assumed default in the event the user didn't provide it.  The modules themselves should not need any updates here

### LINKED ISSUE #225: Base Module Comment
* User/IP Enriched data as a comment

### PR DESCRIPTION
**Pull request by briandelmsft**
Fixes #218 
Fixes #225 

### Test Deployment for this PR:

[Deploy to Azure](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Fdeploy_test%2FDeploy%2Fazuredeploy.json/createUIDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fbriandelmsft%2FSentinelAutomationModules%2Fdeploy_test%2FDeploy%2FcreateUiDefinition.json)

### CODE REVIEW

**Comment by briandelmsft** [comment]
@piaudonn can you try this one out using the link above?  This takes all the true/false options for all modules and makes them default to true and hidden in the connector under the 'add new parameter' menu.  If you already have the connector in a logic app with those values configured, they will be maintained but when you add the connector new they won't be shown unless you add them

Additionally, it adds a User and IP enrichment comment in the base module.

**Comment by piaudonn** [comment]
Starting testing ⏱️

**Comment by briandelmsft** [comment]
@piaudonn good catch, i changed the logic of the comment in 2d632a6 to bring back the friendly name if the enriched UPN is not present

```
coalesce(item()?['userPrincipalName'], concat(item()?['RawEntity']?['friendlyName'], ' (Unresolved Entity)'))
```
image

**Comment by piaudonn** [comment]
image

Lovely !

**Review by piaudonn — APPROVED** [review]
✅ new deployment
✅ update deployment

**Pull request merged**
