### PR TITLE
Update permission script

### LINKED ISSUE #445: [BUG] DeployPermissions.ps1
There may be an issue with the newest versions of the PowerShell modules no longer working with the builtin PowerShell, now seem to only work with 7.

image

### LINKED ISSUE #450: Suggestion to add more steps into documentation of GrantPermissions.ps1 script
Adding more steps into documentation before execution of GrantPermissions.ps1 script 

image

I would suggest we clearly add few more notes in the documentation to have this fixed. Such as mentioning:-

1) To not forget and Install Powershell 7 module
2) Launch Powershell 7 and execute below set of commands:-

Install-Module -Name Az -Repository PSGallery -Force
Install-Module Microsoft.Graph.Applications -Scope CurrentUser -Force -AllowClobber
Connect-AzAccount
Connect-MgGraph

3) And then running the GrantPermissions.ps1 script

### PR DESCRIPTION
**Pull request by piaudonn**
Parameterized the script.
Added comment-based help section.
Added check to detect if the script runs in Cloud Shell and adapt by using device code.
Added an input parameter to request for device code.

* Fixes #445 
* Fixes #450

### CODE REVIEW

**Comment by piaudonn** [comment]
Need to PR at the same time that I udpate the wiki. Let's sync later @briandelmsft

**Comment by briandelmsft** [comment]
@piaudonn mark for review, I'll test and approve, but not merge.  You can merge when ready with the wiki

**Comment by piaudonn** [comment]
Ref #450

**Comment by piaudonn** [comment]
@briandelmsft we'll need to update the aka.ms link to the script once merged.

**Comment by briandelmsft** [comment]
I added a change to the deployment ui to update the default package version to 2.0.2 which has a minor bug fix from 2.0.1 where it was previously pointed

**Review by briandelmsft — APPROVED** [review]

**Pull request merged**
